<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/25 11:06:28
sfConfig::add(array(
  'app_apps_name' => 'FORECAST',
  'app_page_heading' => 'Forecast',
  'app_menu_name' => 'FinanceMenu',
  'app_menu_items' => array (
  0 => 
  array (
    0 => 'Home',
    1 => 'home',
    2 => 'index',
  ),
  1 => 
  array (
    0 => 'Hr Forecast',
    1 => 'hrforecast',
    2 => 'index',
  ),
  2 => 
  array (
    0 => 'Production',
    1 => 'production',
    2 => 'index',
  ),
  3 => 
  array (
    0 => 'Reports',
    1 => 'reports',
    2 => 'index',
  ),
),
  'app_submenu' => NULL,
  'app_ampie_public_path' => '/cityhall/js/ampie/',
  'app_ampie_public_swf' => '/cityhall/js/ampie/ampie.swf',
  'app_amline_public_path' => '/cityhall/js/ampline/',
  'app_amline_public_swf' => '/cityhall/js/amline/amline.swf',
  'app_amcolumn_public_path' => '/cityhall/js/amcolumn/',
  'app_amcolumn_public_swf' => '/cityhall/js/amcolumn/amcolumn.swf',
));
