<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/25 11:06:29
$this->security = array (
  'dailyforecast' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'finance_level_1',
        2 => 'finance_level_2',
      ),
    ),
  ),
  'monthlytrend' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'finance_level_2',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'finance_level_1',
        2 => 'finance_level_2',
      ),
    ),
  ),
);
