<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/22 12:19:01
sfConfig::add(array(
  'app_apps_name' => 'HRIS',
  'app_page_heading' => 'Human Resource',
  'app_menu_name' => 'HumanResourceMenu',
  'app_menu_items' => array (
  0 => 
  array (
    0 => 'DTR',
    1 => 'dtr',
    2 => 'scanin',
  ),
  1 => 
  array (
    0 => 'Home',
    1 => 'dashboard',
    2 => 'dashboard',
  ),
  2 => 
  array (
    0 => 'Employee Info',
    1 => 'employee',
    2 => 'employee',
  ),
  3 => 
  array (
    0 => 'Maintenance',
    1 => 'maintenance',
    2 => 'maintenance',
  ),
  4 => 
  array (
    0 => 'Leave Transaction',
    1 => 'leave',
    2 => 'leave',
  ),
  5 => 
  array (
    0 => 'Timekeeping',
    1 => 'timekeeping',
    2 => 'timekeeping',
  ),
  6 => 
  array (
    0 => 'Contribution',
    1 => 'contribution',
    2 => 'contribution',
  ),
  7 => 
  array (
    0 => 'Payroll',
    1 => 'payroll',
    2 => 'payroll',
  ),
  8 => 
  array (
    0 => 'Reports',
    1 => 'reports',
    2 => 'reports',
  ),
  9 => 
  array (
    0 => 'Utilities',
    1 => 'utilities',
    2 => 'utilities',
  ),
  10 => 
  array (
    0 => 'Business Intel',
    1 => 'businessIntelligence',
    2 => 'businessIntelligence',
  ),
),
  'app_submenu' => NULL,
  'app_ampie_public_path' => '/cityhall/js/ampie/',
  'app_ampie_public_swf' => '/cityhall/js/ampie/ampie.swf',
  'app_amline_public_path' => '/cityhall/js/ampline/',
  'app_amline_public_swf' => '/cityhall/js/amline/amline.swf',
  'app_amcolumn_public_path' => '/cityhall/js/amcolumn/',
  'app_amcolumn_public_swf' => '/cityhall/js/amcolumn/amcolumn.swf',
  'app_amcharts_colors' => array (
  0 => 'FF6600',
  1 => 'FCD202',
  2 => 'B0DE09',
  3 => '2A0CD0',
  4 => '990099',
  5 => '990000',
  6 => '00FF00',
  7 => 'FF00FF',
  8 => '33cccc',
  9 => 'ff0000',
  10 => 'ccffff',
),
));
