<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/02/03 17:14:49
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
);
