<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/25 15:44:46
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'hr_admin',
    ),
  ),
);
