<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/22 12:19:02
$this->security = array (
  'timekeeper' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_timekeeper',
        2 => 'hr_basic',
        3 => 'hr_supervisor',
      ),
    ),
  ),
  'teamassignment' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_timekeeper',
      ),
    ),
  ),
  'displaytimekeeper' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_timekeeper',
      ),
    ),
  ),
  'adjusttime' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_timekeeper',
      ),
    ),
  ),
  'individualpayslip' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'multiplescanin' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'uploadrawdata' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
      ),
    ),
  ),
  'passwordchange' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_timekeeper',
        2 => 'hr_supervisor',
        3 => 'hr_basic',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
);
