<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/02/03 17:14:49
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
