<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/02/18 14:33:28
$this->security = array (
  'individualleaveedit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'individualleaveadd' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'hr_admin',
    ),
  ),
);
