<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/02/02 13:59:15
$this->security = array (
  'attendancelog' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'hiringadd' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'hrlogsearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'workright' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'mfgqoutacalculator' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'svsqoutacalculator' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'requestticket' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
);
