<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/22 16:38:22
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
);
