<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/25 15:44:46
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
