<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/25 11:33:10
$this->security = array (
  'payslipmanualentry' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'hr_admin',
    ),
  ),
);
