<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/23 09:25:22
$this->security = array (
  'leaveapprovalsearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_timekeeper',
      ),
    ),
  ),
  'leaveapplysearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'hr_timekeeper',
        2 => 'hr_user',
      ),
    ),
  ),
  'leavecreditsearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
      ),
    ),
  ),
  'leavesearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
      ),
    ),
  ),
  'leaveemployeeapply' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'hr_admin',
        1 => 'hr_supervisor',
        2 => 'hr_user',
      ),
    ),
  ),
);
