<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/02/03 12:03:52
sfConfig::add(array(
  'sf_logging_enabled' => true,
  'sf_logging_level' => 'err',
  'sf_logging_rotate' => false,
  'sf_logging_period' => 7,
  'sf_logging_history' => 10,
  'sf_logging_purge' => false,
));

$logger = sfLogger::getInstance();
$logger->setLogLevel(constant('SF_LOG_'.strtoupper(sfConfig::get('sf_logging_level'))));

$log = new sfFileLogger();
$log->initialize(array (
  'file' => '/opt/httpd/htdocs_i/symfony/snapps-orion/log/dashboard_prod.log',
));
$logger->registerLogger($log);
