<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/02/03 12:03:52
sfConfig::add(array(
  'app_apps_name' => 'Dashboard Micronclean Singapore',
  'app_menu_name' => 'dashboardMenu',
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
));
