<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/01/22 12:17:34
$this->security = array (
  'index' => 
  array (
    'is_secure' => 'one',
  ),
  'pubpowerconsumptionsearch' => 
  array (
    'is_secure' => 'one',
  ),
  'pubpowerconsumptionadd' => 
  array (
    'is_secure' => 'one',
  ),
  'pubpowerconsumptionedit' => 
  array (
    'is_secure' => 'one',
  ),
  'pubpowerconsumptiondelete' => 
  array (
    'is_secure' => 'one',
  ),
  'pubwaterconsumptionsearch' => 
  array (
    'is_secure' => 'one',
  ),
  'pubwaterconsumptionadd' => 
  array (
    'is_secure' => 'one',
  ),
  'pubwaterconsumptionedit' => 
  array (
    'is_secure' => 'one',
  ),
  'pubwaterconsumptiondelete' => 
  array (
    'is_secure' => 'one',
  ),
  'powerconsumptionsearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'powerconsumptionadd' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'powerconsumptionedit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'powerconsumptiondelete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'waterconsumptionsearch' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'waterconsumptionadd' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'waterconsumptionedit' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'waterconsumptiondelete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'PowerDataEntry',
        2 => 'finance_level_1',
        3 => 'finance_level_2',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'finance_level_1',
        2 => 'finance_level_2',
      ),
    ),
  ),
);
