default:
  is_secure: off
index:
  is_secure: one
pubPowerConsumptionSearch:
  is_secure: one
pubPowerConsumptionAdd:
  is_secure: one
pubPowerConsumptionEdit:
  is_secure: one
pubPowerConsumptionDelete:
  is_secure: one

pubWaterConsumptionSearch:
  is_secure: one
pubWaterConsumptionAdd:
  is_secure: one
pubWaterConsumptionEdit:
  is_secure: one
pubWaterConsumptionDelete:
  is_secure: one
  
powerConsumptionSearch:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]] 
powerConsumptionAdd:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]

powerConsumptionEdit:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]
  
powerConsumptionDelete:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]

waterConsumptionSearch:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]] 
waterConsumptionAdd:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]

waterConsumptionEdit:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]
  
waterConsumptionDelete:
  is_secure: on
  credentials: [[admin, PowerDataEntry, finance_level_1, finance_level_2]]
