<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/01/23 10:00:02
sfConfig::add(array(
  'app_apps_name' => 'MAINTENANCE ENTRY',
  'app_page_heading' => 'MAINTENANCE ENTRY',
  'app_menu_name' => 'MaintenanceEntry',
));
