default:
  is_secure: on
  credentials: [hr_admin]

individualLeaveEdit:
  is_secure: on
  credentials: [[hr_admin, hr_supervisor]]
  
individualLeaveAdd:
  is_secure: on
  credentials: [[hr_admin, hr_supervisor]]  